// <auto-generated />
using System;
using Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Common.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("RoleLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "a4cae062-f7c8-42ae-97c8-c2038cc58937",
                            ConcurrencyStamp = "adbf7237-b20d-4ae1-bc6e-d08f04c20fd0",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR",
                            RoleLevel = 100
                        },
                        new
                        {
                            Id = "56e329b2-a1ff-4211-9893-979d691f11cc",
                            ConcurrencyStamp = "d328a59f-1fdb-4d4a-bcee-852ae8c6f49f",
                            Name = "Manager",
                            NormalizedName = "MANAGER",
                            RoleLevel = 200
                        },
                        new
                        {
                            Id = "9dff8b12-8915-4b34-bcbb-7f0ecedd1129",
                            ConcurrencyStamp = "245bed92-c73f-4428-a9a5-7fa85f05b3fb",
                            Name = "Clerk",
                            NormalizedName = "CLERK",
                            RoleLevel = 300
                        },
                        new
                        {
                            Id = "e5351832-2511-41d5-96ef-fb3a4e58e975",
                            ConcurrencyStamp = "0fedff64-5ac8-411f-a6ce-fe5bfd07df35",
                            Name = "User",
                            NormalizedName = "USER",
                            RoleLevel = 400
                        });
                });

            modelBuilder.Entity("Common.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserUID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Common.Models.CardTransaction", b =>
                {
                    b.Property<Guid>("CardTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CardTransactionID");

                    b.Property<decimal?>("AmountChange")
                        .HasColumnType("smallmoney");

                    b.Property<decimal?>("AmountDiscounted")
                        .HasColumnType("smallmoney");

                    b.Property<decimal?>("AmountReceived")
                        .HasColumnType("smallmoney");

                    b.Property<decimal?>("AmountTotal")
                        .HasColumnType("smallmoney");

                    b.Property<double?>("DiscountPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("TransportCardID")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransportCardTripID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CardTransactionID");

                    b.HasIndex("TransportCardID");

                    b.HasIndex("TransportCardTripID");

                    b.ToTable("CardTransactions");
                });

            modelBuilder.Entity("Common.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EmployeeFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"), 1L, 1);

                    b.Property<string>("EmployeeLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("EmployeeUID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Common.Models.GenEmpUID", b =>
                {
                    b.Property<string>("GeneratedUID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("GeneratedUID");

                    b.Property<int>("GeneratedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GeneratedID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneratedID"), 1001L, 1);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("GeneratedUID");

                    b.ToTable("GenEmpUIDs");
                });

            modelBuilder.Entity("Common.Models.RAWSMARTCARD", b =>
                {
                    b.Property<int>("SmartCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SmartCardID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SmartCardID"), 1L, 1);

                    b.Property<DateTime?>("ActivatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsValid")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("SmartCardName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SmartCardID");

                    b.ToTable("RAWSMARTCARDs");
                });

            modelBuilder.Entity("Common.Models.TrainStation", b =>
                {
                    b.Property<Guid>("TrainStationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TrainStationID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrainStationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainStationNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransportCardTripID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("TrainStationID");

                    b.HasIndex("TransportCardTripID");

                    b.ToTable("TrainStations");

                    b.HasData(
                        new
                        {
                            TrainStationID = new Guid("2a336f84-9030-4952-888c-93bf102f3a0c"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5114),
                            IsActive = true,
                            TrainStationCode = "ST1",
                            TrainStationNumber = 1,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5117)
                        },
                        new
                        {
                            TrainStationID = new Guid("629cab4d-51e9-41de-a28d-5943124e48b6"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5133),
                            IsActive = true,
                            TrainStationCode = "ST2",
                            TrainStationNumber = 2,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5133)
                        },
                        new
                        {
                            TrainStationID = new Guid("68bdee88-f25b-4045-80fe-100202f1601f"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5144),
                            IsActive = true,
                            TrainStationCode = "ST3",
                            TrainStationNumber = 3,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5144)
                        },
                        new
                        {
                            TrainStationID = new Guid("17e4c44b-cac4-4ac9-9978-f9369d9088b6"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5154),
                            IsActive = true,
                            TrainStationCode = "ST4",
                            TrainStationNumber = 4,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5155)
                        },
                        new
                        {
                            TrainStationID = new Guid("0550f021-e5bf-474b-9b01-914fbcd251de"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5164),
                            IsActive = true,
                            TrainStationCode = "ST5",
                            TrainStationNumber = 5,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5164)
                        },
                        new
                        {
                            TrainStationID = new Guid("2760da89-f9bd-42ad-9e51-9a5a4dc4e98c"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5179),
                            IsActive = true,
                            TrainStationCode = "ST6",
                            TrainStationNumber = 6,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5180)
                        },
                        new
                        {
                            TrainStationID = new Guid("06a017bf-6228-4c2b-81ce-77bbb772226d"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5190),
                            IsActive = true,
                            TrainStationCode = "ST7",
                            TrainStationNumber = 7,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5191)
                        },
                        new
                        {
                            TrainStationID = new Guid("ccd58bb3-d32c-44e9-8c39-6602fe8c0d67"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5200),
                            IsActive = true,
                            TrainStationCode = "ST8",
                            TrainStationNumber = 8,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5200)
                        },
                        new
                        {
                            TrainStationID = new Guid("641b09a9-16c7-46bd-a717-441133399d7b"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5210),
                            IsActive = true,
                            TrainStationCode = "ST9",
                            TrainStationNumber = 9,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5211)
                        },
                        new
                        {
                            TrainStationID = new Guid("2b0c21fb-689a-4d8a-9537-4adc1c0cf040"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5222),
                            IsActive = true,
                            TrainStationCode = "ST10",
                            TrainStationNumber = 10,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 15, 55, 48, 288, DateTimeKind.Utc).AddTicks(5222)
                        });
                });

            modelBuilder.Entity("Common.Models.TransportCard", b =>
                {
                    b.Property<int>("TransportCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransportCardID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransportCardID"), 1L, 1);

                    b.Property<string>("CardHolder")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPWDCard")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSeniorCard")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("LoadBalance")
                        .HasColumnType("smallmoney");

                    b.Property<string>("PWDNumber")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RAWSMARTCARDSmartCardID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SCCNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ValidityDate")
                        .HasColumnType("datetime");

                    b.HasKey("TransportCardID");

                    b.HasIndex("RAWSMARTCARDSmartCardID");

                    b.ToTable("TransportCards");
                });

            modelBuilder.Entity("Common.Models.TransportCardTrip", b =>
                {
                    b.Property<Guid>("TransportCardTripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AmountTripCharge")
                        .HasColumnType("smallmoney");

                    b.Property<string>("DestinationStationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasGateIN")
                        .HasColumnType("bit");

                    b.Property<bool>("HasGateOUT")
                        .HasColumnType("bit");

                    b.Property<string>("OriginStationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("TransportCardID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransportCardTripDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TransportCardTripOperatorCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransportCardTripID");

                    b.HasIndex("TransportCardID");

                    b.ToTable("TransportCardTrips");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Common.Models.CardTransaction", b =>
                {
                    b.HasOne("Common.Models.TransportCard", "TransportCard")
                        .WithMany("CardTransactions")
                        .HasForeignKey("TransportCardID");

                    b.HasOne("Common.Models.TransportCardTrip", "TransportCardTrip")
                        .WithMany()
                        .HasForeignKey("TransportCardTripID");

                    b.Navigation("TransportCard");

                    b.Navigation("TransportCardTrip");
                });

            modelBuilder.Entity("Common.Models.Employee", b =>
                {
                    b.HasOne("Common.Models.GenEmpUID", "GenEmpUID")
                        .WithOne("Employee")
                        .HasForeignKey("Common.Models.Employee", "EmployeeUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenEmpUID");
                });

            modelBuilder.Entity("Common.Models.TrainStation", b =>
                {
                    b.HasOne("Common.Models.TransportCardTrip", "TransportCardTrip")
                        .WithMany("TrainStations")
                        .HasForeignKey("TransportCardTripID");

                    b.Navigation("TransportCardTrip");
                });

            modelBuilder.Entity("Common.Models.TransportCard", b =>
                {
                    b.HasOne("Common.Models.RAWSMARTCARD", "RAWSMARTCARD")
                        .WithMany("TransportCards")
                        .HasForeignKey("RAWSMARTCARDSmartCardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RAWSMARTCARD");
                });

            modelBuilder.Entity("Common.Models.TransportCardTrip", b =>
                {
                    b.HasOne("Common.Models.TransportCard", "TransportCard")
                        .WithMany("TransportCardTrips")
                        .HasForeignKey("TransportCardID");

                    b.Navigation("TransportCard");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Common.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Common.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Common.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Common.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Common.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Models.GenEmpUID", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Common.Models.RAWSMARTCARD", b =>
                {
                    b.Navigation("TransportCards");
                });

            modelBuilder.Entity("Common.Models.TransportCard", b =>
                {
                    b.Navigation("CardTransactions");

                    b.Navigation("TransportCardTrips");
                });

            modelBuilder.Entity("Common.Models.TransportCardTrip", b =>
                {
                    b.Navigation("TrainStations");
                });
#pragma warning restore 612, 618
        }
    }
}
