// <auto-generated />
using System;
using Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Common.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Common.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("RoleLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "f900568e-9c20-4fb3-9492-74b289fdea7e",
                            ConcurrencyStamp = "a914e8cb-831c-416f-89eb-ecb81669b980",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR",
                            RoleLevel = 100
                        },
                        new
                        {
                            Id = "5ef268dc-c6b1-4331-b4fd-b82e8fec7b7d",
                            ConcurrencyStamp = "72f94dd3-153f-4eec-a562-cdc1d95e96cc",
                            Name = "Manager",
                            NormalizedName = "MANAGER",
                            RoleLevel = 200
                        },
                        new
                        {
                            Id = "92a7cf92-3402-48dd-8355-1de4bd082d6f",
                            ConcurrencyStamp = "dd85844e-dd4f-407e-8cb9-3c2975e9f88a",
                            Name = "Clerk",
                            NormalizedName = "CLERK",
                            RoleLevel = 300
                        },
                        new
                        {
                            Id = "e5c5fe49-57e7-435a-9eb7-19b2780d61ba",
                            ConcurrencyStamp = "9adc83d0-f1dc-4bb6-9a53-a2eb992a52af",
                            Name = "User",
                            NormalizedName = "USER",
                            RoleLevel = 400
                        });
                });

            modelBuilder.Entity("Common.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserUID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Common.Models.CardTransaction", b =>
                {
                    b.Property<Guid>("CardTransactionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CardTransactionID");

                    b.Property<decimal?>("AmountChange")
                        .HasColumnType("smallmoney");

                    b.Property<decimal?>("AmountDiscounted")
                        .HasColumnType("smallmoney");

                    b.Property<decimal?>("AmountReceived")
                        .HasColumnType("smallmoney");

                    b.Property<decimal?>("AmountTotal")
                        .HasColumnType("smallmoney");

                    b.Property<double?>("DiscountPercentage")
                        .HasColumnType("float");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("TransportCardID")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransportCardTripID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CardTransactionID");

                    b.HasIndex("TransportCardID");

                    b.HasIndex("TransportCardTripID");

                    b.ToTable("CardTransactions");
                });

            modelBuilder.Entity("Common.Models.Employee", b =>
                {
                    b.Property<string>("EmployeeUID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EmployeeFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeID"), 1L, 1);

                    b.Property<string>("EmployeeLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("EmployeeUID");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Common.Models.GenEmpUID", b =>
                {
                    b.Property<string>("GeneratedUID")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("GeneratedUID");

                    b.Property<int>("GeneratedID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GeneratedID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneratedID"), 1001L, 1);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("GeneratedUID");

                    b.ToTable("GenEmpUIDs");
                });

            modelBuilder.Entity("Common.Models.RAWSMARTCARD", b =>
                {
                    b.Property<int>("SmartCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SmartCardID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SmartCardID"), 1L, 1);

                    b.Property<DateTime?>("ActivatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsValid")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("SerialNumber")
                        .HasColumnType("int");

                    b.Property<string>("SmartCardName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SmartCardID");

                    b.ToTable("RAWSMARTCARDs");

                    b.HasData(
                        new
                        {
                            SmartCardID = 1,
                            ActivatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(4025),
                            IsActive = false,
                            IsValid = true,
                            SerialNumber = 111,
                            SmartCardName = "RFID111"
                        },
                        new
                        {
                            SmartCardID = 2,
                            ActivatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(4037),
                            IsActive = false,
                            IsValid = true,
                            SerialNumber = 222,
                            SmartCardName = "RFID222"
                        },
                        new
                        {
                            SmartCardID = 3,
                            ActivatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(4046),
                            IsActive = false,
                            IsValid = true,
                            SerialNumber = 333,
                            SmartCardName = "RFID333"
                        },
                        new
                        {
                            SmartCardID = 4,
                            ActivatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(4054),
                            IsActive = false,
                            IsValid = true,
                            SerialNumber = 444,
                            SmartCardName = "RFID444"
                        },
                        new
                        {
                            SmartCardID = 5,
                            ActivatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(4063),
                            IsActive = false,
                            IsValid = true,
                            SerialNumber = 555,
                            SmartCardName = "RFID555"
                        });
                });

            modelBuilder.Entity("Common.Models.TrainStation", b =>
                {
                    b.Property<Guid>("TrainStationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TrainStationID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrainStationCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainStationNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("TransportCardTripID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime");

                    b.HasKey("TrainStationID");

                    b.HasIndex("TransportCardTripID");

                    b.ToTable("TrainStations");

                    b.HasData(
                        new
                        {
                            TrainStationID = new Guid("6396c2a3-167e-4067-a08a-c9b905b5adeb"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3734),
                            IsActive = true,
                            TrainStationCode = "ST1",
                            TrainStationNumber = 1,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3737)
                        },
                        new
                        {
                            TrainStationID = new Guid("7dabc179-48c3-4ec6-a6bc-843f48321124"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3836),
                            IsActive = true,
                            TrainStationCode = "ST2",
                            TrainStationNumber = 2,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3837)
                        },
                        new
                        {
                            TrainStationID = new Guid("dcf46702-fab8-4b3a-950f-3a87dc02c8f7"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3849),
                            IsActive = true,
                            TrainStationCode = "ST3",
                            TrainStationNumber = 3,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3849)
                        },
                        new
                        {
                            TrainStationID = new Guid("bfc555cb-671f-4bcd-a89f-bd902c83057e"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3858),
                            IsActive = true,
                            TrainStationCode = "ST4",
                            TrainStationNumber = 4,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3858)
                        },
                        new
                        {
                            TrainStationID = new Guid("d8b09dc3-9e5b-4cf2-83f1-55a31f044414"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3868),
                            IsActive = true,
                            TrainStationCode = "ST5",
                            TrainStationNumber = 5,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3868)
                        },
                        new
                        {
                            TrainStationID = new Guid("84c120fa-93ff-4f1d-9f9d-1159d0469db9"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3880),
                            IsActive = true,
                            TrainStationCode = "ST6",
                            TrainStationNumber = 6,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3881)
                        },
                        new
                        {
                            TrainStationID = new Guid("48ebf47e-e168-46b7-a122-ae451f026a96"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3890),
                            IsActive = true,
                            TrainStationCode = "ST7",
                            TrainStationNumber = 7,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3890)
                        },
                        new
                        {
                            TrainStationID = new Guid("30e20419-9d37-40a1-9d7a-bbc117e5d1dd"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3900),
                            IsActive = true,
                            TrainStationCode = "ST8",
                            TrainStationNumber = 8,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3900)
                        },
                        new
                        {
                            TrainStationID = new Guid("97a9fc28-7ec0-46f4-95df-2d2c4f6e2f3f"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3909),
                            IsActive = true,
                            TrainStationCode = "ST9",
                            TrainStationNumber = 9,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3910)
                        },
                        new
                        {
                            TrainStationID = new Guid("0e425127-a70e-4862-b86e-4de8130c95bd"),
                            CreatedBy = "ADMIN",
                            CreatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3924),
                            IsActive = true,
                            TrainStationCode = "ST10",
                            TrainStationNumber = 10,
                            UpdatedBy = "ADMIN",
                            UpdatedDate = new DateTime(2022, 5, 4, 17, 54, 44, 139, DateTimeKind.Utc).AddTicks(3925)
                        });
                });

            modelBuilder.Entity("Common.Models.TransportCard", b =>
                {
                    b.Property<int>("TransportCardID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TransportCardID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransportCardID"), 1L, 1);

                    b.Property<string>("CardHolder")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsPWDCard")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSeniorCard")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("LoadBalance")
                        .HasColumnType("smallmoney");

                    b.Property<string>("PWDNumber")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("RAWSMARTCARDSmartCardID")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SCCNumber")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("ValidityDate")
                        .HasColumnType("datetime");

                    b.HasKey("TransportCardID");

                    b.HasIndex("RAWSMARTCARDSmartCardID");

                    b.ToTable("TransportCards");
                });

            modelBuilder.Entity("Common.Models.TransportCardTrip", b =>
                {
                    b.Property<Guid>("TransportCardTripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("AmountTripCharge")
                        .HasColumnType("smallmoney");

                    b.Property<string>("DestinationStationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasGateIN")
                        .HasColumnType("bit");

                    b.Property<bool>("HasGateOUT")
                        .HasColumnType("bit");

                    b.Property<string>("OriginStationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("TransportCardID")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransportCardTripDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TransportCardTripOperatorCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TransportCardTripID");

                    b.HasIndex("TransportCardID");

                    b.ToTable("TransportCardTrips");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Common.Models.CardTransaction", b =>
                {
                    b.HasOne("Common.Models.TransportCard", "TransportCard")
                        .WithMany("CardTransactions")
                        .HasForeignKey("TransportCardID");

                    b.HasOne("Common.Models.TransportCardTrip", "TransportCardTrip")
                        .WithMany()
                        .HasForeignKey("TransportCardTripID");

                    b.Navigation("TransportCard");

                    b.Navigation("TransportCardTrip");
                });

            modelBuilder.Entity("Common.Models.Employee", b =>
                {
                    b.HasOne("Common.Models.GenEmpUID", "GenEmpUID")
                        .WithOne("Employee")
                        .HasForeignKey("Common.Models.Employee", "EmployeeUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenEmpUID");
                });

            modelBuilder.Entity("Common.Models.TrainStation", b =>
                {
                    b.HasOne("Common.Models.TransportCardTrip", "TransportCardTrip")
                        .WithMany("TrainStations")
                        .HasForeignKey("TransportCardTripID");

                    b.Navigation("TransportCardTrip");
                });

            modelBuilder.Entity("Common.Models.TransportCard", b =>
                {
                    b.HasOne("Common.Models.RAWSMARTCARD", "RAWSMARTCARD")
                        .WithMany("TransportCards")
                        .HasForeignKey("RAWSMARTCARDSmartCardID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RAWSMARTCARD");
                });

            modelBuilder.Entity("Common.Models.TransportCardTrip", b =>
                {
                    b.HasOne("Common.Models.TransportCard", "TransportCard")
                        .WithMany("TransportCardTrips")
                        .HasForeignKey("TransportCardID");

                    b.Navigation("TransportCard");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Common.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Common.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Common.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Common.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Common.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Common.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Common.Models.GenEmpUID", b =>
                {
                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Common.Models.RAWSMARTCARD", b =>
                {
                    b.Navigation("TransportCards");
                });

            modelBuilder.Entity("Common.Models.TransportCard", b =>
                {
                    b.Navigation("CardTransactions");

                    b.Navigation("TransportCardTrips");
                });

            modelBuilder.Entity("Common.Models.TransportCardTrip", b =>
                {
                    b.Navigation("TrainStations");
                });
#pragma warning restore 612, 618
        }
    }
}
